Repository yasu-yo/gitremote2, pull requests merged in 2024-11, with the labels that each got.

#5 A.pyを編集しました#1
  A.py
Labels: 緊急

#6 B.pyを編集しました#2
  B.py
Labels: ちいかわ, 緊急, モモンガ

#7 C.pyを編集しました#4
  C.py
Labels: 緊急, モモンガ

#8 D.pyを編集しました #3
  D.py
Labels: ちいかわ, 緊急, モモンガ
